### ISSUE TITLE
print_tree_high_level segfaults while processing 6 byte html file

### ISSUE THREAD

**Issue by geeknik** [lexborisov/myhtml#27]
I decided to take your software for a spin with my favorite tool, American Fuzzy Lop, and I found that this html snippet

```
<!--!>
```

causes a segfault in the print_tree_high_level binary:

```
(gdb) r out2/crashes/test00.html
Starting program: /home/geeknik/myhtml/bin/print_tree_high_level out2/crashes/test00.html
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7813700 (LWP 16841)]
[New Thread 0x7ffff7012700 (LWP 16849)]
[New Thread 0x7ffff6811700 (LWP 16854)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6811700 (LWP 16854)]
0x0000000000434380 in myhtml_string_append_with_preprocessing (
    str=0x7ffff7e48020, buff=0x826254 "!>", length=18446744073709551614)
    at mystring.c:490
490	        if(u_buff[i] == 0x0D)
(gdb) list
485	    unsigned char *data = (unsigned char*)str->data;
486	    const unsigned char *u_buff = (unsigned char*)buff;
487	    
488	    for (size_t i = 0; i < length; i++)
489	    {
490	        if(u_buff[i] == 0x0D)
491	        {
492	            data[str->length] = 0x0A;
493	            
494	            if((i+1) < length && u_buff[(i + 1)] == 0x0A) {
(gdb) bt
#0  0x0000000000434380 in myhtml_string_append_with_preprocessing (
    str=0x7ffff7e48020, buff=0x826254 "!>", length=18446744073709551614)
    at mystring.c:490
#1  0x0000000000474484 in myhtml_parser_add_text ()
#2  0x0000000000474ad0 in myhtml_parser_worker ()
#3  0x000000000043f9be in mythread_function_batch (arg=0x843390)
    at thread.c:754
#4  0x00007ffff7bc70a4 in start_thread (arg=0x7ffff6811700)
    at pthread_create.c:309
#5  0x00007ffff78fc87d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

Running this under Valgrind caused runaway memory and swap usage, rendering the VM useless until I rebooted it.

**Comment by lexborisov** [comment]
Thank you so much! You helped to find a forgotten once problem. Now is fixed!

**Comment by kostya** [comment]
how you test it without unit tests?

**Comment by lexborisov** [comment]
Before commit is being tested for compliance with the specification (about 1700 tests), + same tests under valgrind.
And parsing 61000+ html pages. 

In the future, will unit tests coverage. who have helped
