### ISSUE TITLE
html2sexpr segfault in _myhtml_string_append_char_references_state_end (mystring.c:327)

### ISSUE THREAD

**Issue by geeknik** [lexborisov/myhtml#28]
While fuzzing myhtml with American Fuzzy Lop, I found that this string:

```
&#88000000000000000000
```

seems to trigger stack corruption and crashes html2sexpr like so:

```
Starting program: /home/geeknik/myhtml/bin/html2sexpr test00.html
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7813700 (LWP 125778)]
[New Thread 0x7ffff7012700 (LWP 125811)]
[New Thread 0x7ffff6811700 (LWP 125815)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6811700 (LWP 125815)]
0x000000000041838f in _myhtml_string_append_char_references_state_end (chunk=chunk@entry=0x7ffff6810e10, 
    str=str@entry=0x7ffff7e48020) at mystring.c:327
327	        chunk->l_data = replacement_character[chunk->l_data];
(gdb) bt
#0  0x000000000041838f in _myhtml_string_append_char_references_state_end (chunk=chunk@entry=0x7ffff6810e10, 
    str=str@entry=0x7ffff7e48020) at mystring.c:327
#1  0x00000000004189ab in myhtml_string_append_charef_end (chunk=chunk@entry=0x7ffff6810e10, str=str@entry=0x7ffff7e48020)
    at mystring.c:457
#2  0x0000000000475d97 in myhtml_parser_add_text_with_charef (tree=0x84d540, string=string@entry=0x7ffff7e48020, 
    text=<optimized out>, begin=0, length=22, is_attibutes=is_attibutes@entry=false) at parser.c:212
#3  0x000000000047645b in myhtml_parser_worker (thread_id=<optimized out>, qnode=0x7ffff7fac010) at parser.c:269
#4  0x00000000004244ae in mythread_function_batch (arg=0x84b390) at thread.c:754
#5  0x00007ffff7bc70a4 in start_thread (arg=0x7ffff6811700) at pthread_create.c:309
#6  0x00007ffff78fc87d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) list
322	    
323	    /* 4 is max utf8 byte + \0 */
324	    MyHTML_STRING_REALLOC_IF_NEED(str, 5, 12);
325	    
326	    if(chunk->l_data <= 0x9F)
327	        chunk->l_data = replacement_character[chunk->l_data];
328	    else if(chunk->l_data >= 0xD800 && chunk->l_data <= 0xDFFF)
329	        chunk->l_data = replacement_character[0];
330	    else if(chunk->l_data > 0x10FFFF)
331	        chunk->l_data = replacement_character[0];
```

```
valgrind -q ../../html2sexpr test00.html
==19305== Thread 4:
==19305== Invalid read of size 8
==19305==    at 0x41838F: _myhtml_string_append_char_references_state_end (mystring.c:327)
==19305==    by 0x4189AA: myhtml_string_append_charef_end (mystring.c:457)
==19305==    by 0x475D96: myhtml_parser_add_text_with_charef (parser.c:212)
==19305==    by 0x47645A: myhtml_parser_worker (parser.c:269)
==19305==    by 0x4244AD: mythread_function_batch (thread.c:754)
==19305==    by 0x4E3D0A3: start_thread (pthread_create.c:309)
==19305==  Address 0x29f66e0c53497340 is not stack'd, malloc'd or (recently) free'd
==19305== 
==19305== 
==19305== Process terminating with default action of signal 11 (SIGSEGV)
==19305==  General Protection Fault
==19305==    at 0x41838F: _myhtml_string_append_char_references_state_end (mystring.c:327)
==19305==    by 0x4189AA: myhtml_string_append_charef_end (mystring.c:457)
==19305==    by 0x475D96: myhtml_parser_add_text_with_charef (parser.c:212)
==19305==    by 0x47645A: myhtml_parser_worker (parser.c:269)
==19305==    by 0x4244AD: mythread_function_batch (thread.c:754)
==19305==    by 0x4E3D0A3: start_thread (pthread_create.c:309)
Killed
```

**Comment by lexborisov** [comment]
Thank you! Fixed
